FROM node:14

WORKDIR /usr/src/app

COPY packages/keycloak-client ./packages/keycloak-client
COPY packages/matrix-spacebot ./packages/matrix-spacebot
COPY package.json .
COPY yarn.lock .
COPY lerna.json .
COPY tsconfig.json .

RUN mkdir /data
RUN yarn install --loglevel notice

EXPOSE 3000

CMD [ "yarn", "--cwd", "packages/matrix-spacebot", "run", "start" ]