FROM node:14

WORKDIR /usr/src/app

COPY packages/emails ./packages/emails
COPY packages/gocardless-client ./packages/gocardless-client
COPY packages/keycloak-client ./packages/keycloak-client
COPY packages/gocardless-webhook ./packages/gocardless-webhook
COPY package.json .
COPY yarn.lock .
COPY lerna.json .
COPY tsconfig.json .

RUN yarn install --loglevel notice

EXPOSE 3000

CMD [ "yarn", "--cwd", "packages/gocardless-webhook", "run", "start" ]