FROM node:14

WORKDIR /usr/src/app

RUN npm i lerna -g --loglevel notice

RUN mkdir /data

COPY package*.json ./
RUN yarn install --loglevel notice

COPY packages/gocardless-client ./packages/gocardless-client
COPY packages/keycloak-client ./packages/keycloak-client
COPY packages/gocardless-hasura ./packages/gocardless-hasura

COPY lerna.json .
COPY tsconfig.json .
RUN lerna bootstrap
RUN lerna run build

EXPOSE 3000

CMD [ "node", "packages/gocardless-hasura/lib/index.js" ]