FROM node:14

WORKDIR /usr/src/app

COPY packages/mosquitto-oauth ./packages/mosquitto-oauth
COPY package.json .
COPY yarn.lock .
COPY lerna.json .
COPY tsconfig.json .

RUN yarn install --loglevel notice

EXPOSE 3000

CMD [ "yarn", "--cwd", "packages/mosquitto-oauth", "run", "start" ]