name: Build and push Docker images

on: [push]

jobs:
  github:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
          install: true

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
        ${{ runner.os }}-buildx-

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: gocardless-hasura - Build and push
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile.gocardless-hasura
          push: true
          tags: teessidehackspace/gocardless-hasura:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: gocardless-webhook - Build and push
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile.gocardless-webhook
          push: true
          tags: teessidehackspace/gocardless-webhook:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: matrix-spacebot - Build and push
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile.matrix-spacebot
          push: true
          tags: teessidehackspace/matrix-spacebot:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: mosquitto-oauth - Build and push
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile.mosquitto-oauth
          push: true
          tags: teessidehackspace/mosquitto-oauth:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
