name: Build and push Docker images

on: [push]

jobs:
  github:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
          install: true

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: gocardless-hasura - Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.gocardless-hasura
          platforms: linux/amd64,linux/arm64,linux/386
          push: true
          tags: teessidehackspace/gocardless-hasura:latest

      - name: gocardless-webhook - Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.gocardless-webhook
          platforms: linux/amd64,linux/arm64,linux/386
          push: true
          tags: teessidehackspace/gocardless-webhook:latest

      - name: matrix-spacebot - Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.matrix-spacebot
          platforms: linux/amd64,linux/arm64,linux/386
          push: true
          tags: teessidehackspace/matrix-spacebot:latest
